Intro to numpy broadcasting
-----------------------------

In [67]:
import numpy as np

In [68]:
a = np.ones((3,4), dtype=np.int32)

In [69]:
print a

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [70]:
# the multiplication is "broadcast" over the whole array:
print a * 3

[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


Doing operations over a whole array at the speed of C -- key to numpy performance.

Regular python lists and comprehensions:

In [71]:
l = range(10000)

In [72]:
# using regular python list comprehensions
%timeit [i*3 for i in l]

1000 loops, best of 3: 381 µs per loop


Now the numpy way:

In [73]:
a = np.arange(10000) # create an array

In [75]:
timeit a * 3

The slowest run took 5.24 times longer than the fastest. This could mean that an intermediate result is being cached 
100000 loops, best of 3: 8.43 µs per loop


### in-place operations

One of the primary reasons "augemented assignment" was added to Python 
is support in-place operations:
    `+=`, `*=`, etc...

In [76]:
a = np.arange(10)
print a

[0 1 2 3 4 5 6 7 8 9]


In [77]:
a+=3
print a

[ 3  4  5  6  7  8  9 10 11 12]


A was changed in place -- no new memory allocation, loop at the speed of C.

How do you broadcast to multiple dimensions?

In [97]:
x = np.linspace(0,9,4,dtype=np.int32)
print x
y = np.linspace(100,200,3,dtype=np.int32)
print y

[0 3 6 9]
[100 150 200]


In [98]:
x.shape = (1, -1) # one row, figure out the columns
y.shape = (-1, 1) # figure out the rows, one column
# now we 2-dim arrays
print "X: \n", x
print "Y: \n",y

X: 
[[0 3 6 9]]
Y: 
[[100]
 [150]
 [200]]


In [99]:
a = np.arange(4)
#x = np.arange(8).reshape(2,4)
print a.shape
print x.shape
print
print "%s * %s\n" %( x, a )
print "result = \n", a  * x

(4,)
(1, 4)

[[0 3 6 9]] * [0 1 2 3]

result = 
[[ 0  3 12 27]]


In [88]:
#a.shape = (1,4)
print a.shape
print y.shape
print
print "%s * %s\n " %( y, a )
print "result = \n", a  * y

(4,)
(3, 1)

[[100]
 [150]
 [200]] * [0 1 2 3]
 
result = 
[[  0 100 200 300]
 [  0 150 300 450]
 [  0 200 400 600]]


In [105]:
x = np.arange(12).reshape((3,4))
y = np.arange(12).reshape((3,4)) * 10
print x
print
print y


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]


In [106]:
print x + y

[[  0  11  22  33]
 [ 44  55  66  77]
 [ 88  99 110 121]]


In [59]:
z = np.array([100, 200, 300, 400])

In [109]:
print z

[100 200 300 400]


In [61]:
x.shape

(3, 4)

In [62]:
z.shape

(4,)

In [111]:
z * x

array([[   0,  200,  600, 1200],
       [ 400, 1000, 1800, 2800],
       [ 800, 1800, 3000, 4400]])

In [113]:
z = np.array([100, 200, 300])
z.shape = (3,1)
print z

[[100]
 [200]
 [300]]


In [38]:
z * x

array([[   0,  100,  200,  300],
       [ 800, 1000, 1200, 1400],
       [2400, 2700, 3000, 3300]])