Assorted numpy Constructors
-----------------------------

In [1]:
#Always need to import it... 
import numpy as np

In [14]:
# from scratch:
a = np.ones((3,2)) # default dtype is float64
print a

[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]


In [7]:
a.dtype


dtype('float64')

In [41]:
print np.zeros((2,3), dtype=np.int32)

[[0 0 0]
 [0 0 0]]


In [25]:
print np.empty((3,3), dtype=np.float) # not initilized!

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [20]:
# for a range:
# integers (much like the regular range...)
print np.arange(2, 10, .5)

[ 2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5  8.   8.5  9.
  9.5]


In [43]:
# use random
print np.random.rand(10,2)

[[ 0.96086897  0.94790953]
 [ 0.46289386  0.9276244 ]
 [ 0.69697555  0.4859792 ]
 [ 0.29748225  0.25937413]
 [ 0.24042061  0.63652866]
 [ 0.49533615  0.588826  ]
 [ 0.13580269  0.39329092]
 [ 0.68504981  0.87178977]
 [ 0.98341934  0.79908849]
 [ 0.825975    0.77459968]]


In [45]:
print np.random.randint(10,size=(2,2))

[[2 6]
 [0 6]]


In [60]:
# for floats
# from zero to 1
print np.linspace(0,1)

[ 0.          0.02040816  0.04081633  0.06122449  0.08163265  0.10204082
  0.12244898  0.14285714  0.16326531  0.18367347  0.20408163  0.2244898
  0.24489796  0.26530612  0.28571429  0.30612245  0.32653061  0.34693878
  0.36734694  0.3877551   0.40816327  0.42857143  0.44897959  0.46938776
  0.48979592  0.51020408  0.53061224  0.55102041  0.57142857  0.59183673
  0.6122449   0.63265306  0.65306122  0.67346939  0.69387755  0.71428571
  0.73469388  0.75510204  0.7755102   0.79591837  0.81632653  0.83673469
  0.85714286  0.87755102  0.89795918  0.91836735  0.93877551  0.95918367
  0.97959184  1.        ]


In [64]:
# you can do arange with floats, too
# but it can get wierd with floating point error!
print np.arange(0.1,1.1, 0.1, dtype=np.float)

[ 0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1. ]


In [66]:
# if you are a math/scicnce geek, adn want a log axis...
print np.logspace(0, 3)

[    1.             1.1513954      1.32571137     1.52641797     1.75751062
     2.02358965     2.32995181     2.6826958      3.0888436      3.55648031
     4.09491506     4.71486636     5.42867544     6.25055193     7.19685673
     8.28642773     9.54095476    10.98541142    12.64855217    14.56348478
    16.76832937    19.30697729    22.22996483    25.59547923    29.47051703
    33.93221772    39.06939937    44.98432669    51.79474679    59.63623317
    68.6648845     79.06043211    91.0298178    104.81131342   120.67926406
   138.94954944   159.98587196   184.20699693   212.09508879   244.20530945
   281.1768698    323.74575428   372.75937203   429.19342601   494.17133613
   568.9866029    655.12855686   754.31200634   868.51137375  1000.        ]


In [47]:
# from existing data:
# maybe the most common constructor 
a = np.array([(1, 2),
                (3, 4.0),
                (5, 6)]) # auto-determined dtype
print a

[[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]]


In [48]:
a.shape

(3, 2)

In [49]:
# maybe an array?
a = np.arange(5)
b = np.asarray(a)
print a is b

True


In [50]:
#or not:
a = range(5)
b = np.asarray(a)
print a is b

False


In [74]:
x = np.random.randint(100,size=(10,10))
print x

[[ 7 92 89 87 64 95 29 68 82 88]
 [54 55 29 61 43 28 24 21 91 17]
 [49 76 12 37 63 93 40 14 62 75]
 [36 39 84 14 59 59 13 27 36 65]
 [61 93 51 43 31 17 98 18 17 10]
 [65 10 25 70 89  1 29 11 10 54]
 [19 25 29 74 16 58  4 22 43 60]
 [29 16 43 18 31 12 73 83 13 69]
 [64  9 71 77 36 44 80  9 39 27]
 [85 45 57 25 14 39  2 26 82 88]]


In [76]:
print x.diagonal(offset=1)

[92 29 37 59 17 29 22 13 27]
